### ISSUE TITLE
Consider bundling release files via GitHub WebUI

### ISSUE THREAD

**Issue by larpon** [Mainman002/Wacom-Bamboo-Settings-Gui#1]
Hi,

If you do [releases via the webinterface](https://github.com/Mainman002/Wacom-Bamboo-Settings-Gui/releases/new) - it let's you attach additional binary files - like the linux binary `.zip` files that currently lives [inside the repository](https://github.com/Mainman002/Wacom-Bamboo-Settings-Gui/tree/master/Linux%20APP%20Exports)

Just a thought

More on releasing [here](https://help.github.com/articles/creating-releases/)

**Comment by Mainman002** [comment]
oh yeah true, ok I've setup 2 releases
